Repository Pre-Onboarding-FE-Team07/wanted-codestates-project-7-5-1, pull requests merged in 2022-02, with the labels that each got.

#7 Feat: Product Page 좌측 섹션 구현
  public/index.html
  src/component/Product/Aside.jsx
  src/component/Product/Attribute.jsx
  src/component/Product/AttributeList.jsx
  src/component/Product/Section.jsx
  src/component/Product/SectionTitle.jsx
  src/page/ProductPage.jsx
Labels: enhancement

#9 Feat: ErrorMessage 컴포넌트 구현
  src/components/ErrorMessage.jsx
Labels: enhancement

#10 Fix: rewrite 규칙 수정
  webpack.config.js
Labels: enhancement

#16 Feature/8/product page logic
  src/components/Product/Aside.jsx
  src/components/Product/Attribute.jsx
  src/components/Product/AttributeList.jsx
  src/components/Product/Recommends.jsx
  src/pages/ProductPage.jsx
Labels: enhancement

#17 Feature/3/loading UI
  src/components/Loading.jsx
  tailwind.config.js
Labels: enhancement

#14 Feat: <ProductDetails /> 컴포넌트 구현
  src/components/ProductDetails.jsx
Labels: enhancement

#20 Feat: Recommends 컴포넌트에 Card, ProductDetails 연결
  src/components/Product/Recommends.jsx
Labels: enhancement

#23 Fix/21/product page
  package.json
  src/components/Card.jsx
  src/components/Header.jsx
  src/components/Main/SearchBar.jsx
  src/components/Main/Title.jsx
  src/components/Product/Aside.jsx
  src/components/Product/Recommends.jsx
  src/index.jsx
  src/pages/MainPage.jsx
  src/pages/ProductPage.jsx
  src/styles/global.pcss
  webpack.config.js
  yarn.lock
Labels: bug

#32 Feat: 이미지 클릭 시 해당 이미지 Product Page로 라우팅
  .eslintrc.json
  src/components/Card.jsx
  src/components/Main/SearchBar.jsx
  src/components/Product/Aside.jsx
  src/components/Product/Attribute.jsx
  src/components/Product/Recommends.jsx
  src/hooks/useSearch.js
  src/pages/KeywordPage.jsx
  src/utilities/fetchData.js
Labels: enhancement

#33 Hotfix: KeywordPage 버그 해결
  src/pages/KeywordPage.jsx
Labels: bug

#40 Feat: Pagination
  src/components/Product/Recommends.jsx
  src/pages/KeywordPage.jsx
  src/pages/ProductPage.jsx
Labels: enhancement

#45 Docs: Update README.md
  README.md
Labels: documentation
